import { supabase } from '../supabaseClient';

/**
 * Class Management Service
 *
 * Handles all class-related operations including CRUD operations,
 * membership management, and invite code handling.
 */

/**
 * Create a new class (teacher only)
 * @param {Object} classData - Class information
 * @param {string} classData.name - Class name
 * @param {string} classData.description - Class description
 * @returns {Promise<Object>} Created class with invite code
 */
export async function createClass({ name, description }) {
  const { data: { user } } = await supabase.auth.getUser();

  if (!user) {
    throw new Error('User not authenticated');
  }

  const { data, error } = await supabase
    .from('classes')
    .insert([
      {
        teacher_id: user.id,
        name,
        description,
        // invite_code will be auto-generated by trigger
      },
    ])
    .select()
    .single();

  if (error) {
    console.error('Error creating class:', error);
    throw error;
  }

  return data;
}

/**
 * Get all classes for current user (teacher or student)
 * @returns {Promise<Array>} Array of classes
 */
export async function getMyClasses() {
  const { data: { user } } = await supabase.auth.getUser();

  if (!user) {
    throw new Error('User not authenticated');
  }

  // Get user's role
  const { data: profile } = await supabase
    .from('profiles')
    .select('role')
    .eq('id', user.id)
    .single();

  if (profile?.role === 'teacher') {
    // Get classes where user is the teacher
    const { data, error } = await supabase
      .from('classes')
      .select(`
        *,
        teacher:profiles!classes_teacher_id_fkey(id, username, avatar_url),
        members:class_memberships(count)
      `)
      .eq('teacher_id', user.id)
      .eq('is_active', true)
      .order('created_at', { ascending: false });

    if (error) throw error;
    return data || [];
  } else {
    // Get classes where user is a member
    const { data, error } = await supabase
      .from('class_memberships')
      .select(`
        *,
        class:classes(
          *,
          teacher:profiles!classes_teacher_id_fkey(id, username, avatar_url)
        )
      `)
      .eq('student_id', user.id)
      .eq('status', 'active');

    if (error) throw error;
    return data?.map(m => m.class) || [];
  }
}

/**
 * Get class details by ID
 * @param {string} classId - Class ID
 * @returns {Promise<Object>} Class details with members
 */
export async function getClassById(classId) {
  const { data, error } = await supabase
    .from('classes')
    .select(`
      *,
      teacher:profiles!classes_teacher_id_fkey(id, username, avatar_url, role, verification_status),
      memberships:class_memberships(
        *,
        student:profiles(id, username, avatar_url, vark_visual, vark_auditory, vark_reading_writing, vark_kinesthetic)
      )
    `)
    .eq('id', classId)
    .single();

  if (error) {
    console.error('Error fetching class:', error);
    throw error;
  }

  return data;
}

/**
 * Update class information (teacher only)
 * @param {string} classId - Class ID
 * @param {Object} updates - Fields to update
 * @returns {Promise<Object>} Updated class
 */
export async function updateClass(classId, updates) {
  const { data, error } = await supabase
    .from('classes')
    .update(updates)
    .eq('id', classId)
    .select()
    .single();

  if (error) {
    console.error('Error updating class:', error);
    throw error;
  }

  return data;
}

/**
 * Delete/archive a class (teacher only)
 * @param {string} classId - Class ID
 * @returns {Promise<void>}
 */
export async function deleteClass(classId) {
  const { error } = await supabase
    .from('classes')
    .update({ is_active: false })
    .eq('id', classId);

  if (error) {
    console.error('Error deleting class:', error);
    throw error;
  }
}

/**
 * Join a class using invite code (student)
 * @param {string} inviteCode - 6-character invite code
 * @returns {Promise<Object>} Class that was joined
 */
export async function joinClassWithCode(inviteCode) {
  const { data: { user } } = await supabase.auth.getUser();

  if (!user) {
    throw new Error('User not authenticated');
  }

  // Find class by invite code
  const { data: classData, error: classError } = await supabase
    .from('classes')
    .select('*')
    .eq('invite_code', inviteCode.toUpperCase())
    .eq('is_active', true)
    .single();

  if (classError || !classData) {
    throw new Error('Invalid invite code or class not found');
  }

  // Check if already a member
  const { data: existingMembership } = await supabase
    .from('class_memberships')
    .select('*')
    .eq('class_id', classData.id)
    .eq('student_id', user.id)
    .single();

  if (existingMembership) {
    if (existingMembership.status === 'active') {
      throw new Error('You are already a member of this class');
    } else {
      // Reactivate membership
      const { error: updateError } = await supabase
        .from('class_memberships')
        .update({ status: 'active', joined_at: new Date().toISOString() })
        .eq('id', existingMembership.id);

      if (updateError) throw updateError;
      return classData;
    }
  }

  // Create new membership
  const { error: membershipError } = await supabase
    .from('class_memberships')
    .insert([
      {
        class_id: classData.id,
        student_id: user.id,
        status: 'active',
      },
    ]);

  if (membershipError) {
    console.error('Error joining class:', membershipError);
    throw membershipError;
  }

  return classData;
}

/**
 * Leave a class (student)
 * @param {string} classId - Class ID
 * @returns {Promise<void>}
 */
export async function leaveClass(classId) {
  const { data: { user } } = await supabase.auth.getUser();

  if (!user) {
    throw new Error('User not authenticated');
  }

  const { error } = await supabase
    .from('class_memberships')
    .update({ status: 'removed' })
    .eq('class_id', classId)
    .eq('student_id', user.id);

  if (error) {
    console.error('Error leaving class:', error);
    throw error;
  }
}

/**
 * Remove a student from class (teacher only)
 * @param {string} classId - Class ID
 * @param {string} studentId - Student ID to remove
 * @returns {Promise<void>}
 */
export async function removeStudentFromClass(classId, studentId) {
  const { error } = await supabase
    .from('class_memberships')
    .update({ status: 'removed' })
    .eq('class_id', classId)
    .eq('student_id', studentId);

  if (error) {
    console.error('Error removing student:', error);
    throw error;
  }
}

/**
 * Get class member count
 * @param {string} classId - Class ID
 * @returns {Promise<number>} Number of active members
 */
export async function getClassMemberCount(classId) {
  const { count, error } = await supabase
    .from('class_memberships')
    .select('*', { count: 'exact', head: true })
    .eq('class_id', classId)
    .eq('status', 'active');

  if (error) {
    console.error('Error counting members:', error);
    return 0;
  }

  return count || 0;
}
